##########################
##                      ##
##  Method of sections  ##
##                      ##
##########################

faster.convergence.full.param<-function(c,
                                        age                   =NA,
                                        BW                    =NA,
                                        height                =NA,
                                        Gender                =NA,
                                        TSTART                =NA,
                                        TSTOP                 =NA,
                                        DT                    =NA,
                                        exposure_duration     =NA, 
                                        age_start_occ_exp     =NA,
                                        age_stop_occ_exp      =NA, 
                                        age_start_menstruation=NA,
                                        age_stop_menstruation =NA,
                                        BWbirth               =NA,    
                                        MFV                   =NA,
                                        HR                    =NA,
                                        SDLun                 =NA,
                                        SDH                   =NA,
                                        SDK                   =NA,
                                        SDSto                 =NA,
                                        SDInt                 =NA,
                                        SDSpl                 =NA,
                                        SDPan                 =NA,
                                        SDL                   =NA,
                                        SDBon                 =NA,
                                        SDSk                  =NA,
                                        SDAdi                 =NA,
                                        SDBra                 =NA,
                                        SDThy                 =NA,
                                        SDGon                 =NA,
                                        SDB                   =NA,
                                        SDRem                 =NA,
                                        QfilC                 =NA,
                                        Htc                   =NA,
                                        VplasC                =NA,
                                        VartC                 =NA,
                                        VvenC                 =NA,
                                        SkinThickness         =NA,
                                        fss                   =NA,
                                        hsc                   =NA,
                                        hve                   =NA,
                                        ffatsc                =NA,
                                        ffatve                =NA,
                                        ffatepi               =NA,
                                        ffatbl                =NA,
                                        Kpcell                =NA, # cm/h
                                        Drinkrate             =NA, # mL/kg/d
                                        MW                    =NA,
                                        logP                  =NA,
                                        VP                    =NA,
                                        Kpve                  =NA,
                                        Kpsc                  =NA,
                                        Oralexpo              =NA,
                                        Drinkconc             =NA,
                                        Cinh                  =NA,
                                        Cdermal               =NA,
                                        Tmc                   =NA,
                                        Kt                    =NA,
                                        kurinec               =NA,
                                        CLfaeces              =NA,
                                        Free                  =NA,
                                        PL                    =NA,
                                        PF                    =NA,
                                        PK                    =NA,
                                        PSk                   =NA,
                                        PR                    =NA,
                                        PG                    =NA,
                                        PLun                  =NA,
                                        maternal              =NA,
                                        PT                    =NA,
                                        Ratio                 =NA,
                                        DECLINE               =NA,
                                        Milkconsumption       =NA,
                                        Aartbirth             =NA,
                                        Avenbirth             =NA,
                                        AGbirth               =NA,
                                        ALbirth               =NA,
                                        AFbirth               =NA,
                                        AKbirth               =NA,
                                        ALunbirth             =NA,
                                        ASkbirth              =NA,
                                        ARbirth               =NA,
                                        Afilbirth             =NA,
                                        Adelaybirth           =NA,
                                        Aurinebirth           =NA,
                                        FUN="joost.model",max.loops=10,max.diff=0.01) {
                             
  
  # fixed

  ## Initial value (μg/kg/day)
  x<-y<-numeric(0)
  
  x[1]<-0
  x[2]<-c
  y[1]<-eval(parse(text=parse(text=paste0(FUN,"("                   ,
                                          "age="                    ,age,
                                          ",BW="                    ,BW,
                                          ",height="                ,height,
                                          ",Gender='"               ,Gender,
                                          "',TSTART="               ,TSTART,
                                          ",TSTOP="                 ,TSTOP,                
                                          ",DT="                    ,DT,                  
                                          ",exposure_duration="     ,exposure_duration,
                                          ",age_start_occ_exp="     ,age_start_occ_exp,
                                          ",age_stop_occ_exp="      ,age_stop_occ_exp,
                                          ",age_start_menstruation=",age_start_menstruation,
                                          ",age_stop_menstruation=" ,age_stop_menstruation,
                                          ",BWbirth="               ,BWbirth,   
                                          ",MFV="                   ,MFV,
                                          ",HR="                    ,HR,  
                                          ",SDLun="                 ,SDLun,     
                                          ",SDH="                   ,SDH,   
                                          ",SDK="                   ,SDK,   
                                          ",SDSto="                 ,SDSto,     
                                          ",SDInt="                 ,SDInt,     
                                          ",SDSpl="                 ,SDSpl,     
                                          ",SDPan="                 ,SDPan,     
                                          ",SDL="                   ,SDL,   
                                          ",SDBon="                 ,SDBon,     
                                          ",SDSk="                  ,SDSk,    
                                          ",SDAdi="                 ,SDAdi,     
                                          ",SDBra="                 ,SDBra,     
                                          ",SDThy="                 ,SDThy,   
                                          ",SDGon="                 ,SDGon, 
                                          ",SDB="                   ,SDB, 
                                          ",SDRem="                 ,SDRem,   
                                          ",QfilC="                 ,QfilC,
                                          ",Htc="                   ,Htc,
                                          ",VplasC="                ,VplasC,
                                          ",VartC="                 ,VartC,
                                          ",VvenC="                 ,VvenC,
                                          ",SkinThickness="         ,SkinThickness,
                                          ",fss="                   ,fss,
                                          ",hsc="                   ,hsc,
                                          ",hve="                   ,hve,
                                          ",ffatsc="                ,ffatsc,
                                          ",ffatve="                ,ffatve,
                                          ",ffatepi="               ,ffatepi,
                                          ",ffatbl="                ,ffatbl,
                                          ",Kpcell="                ,Kpcell, 
                                          ",Drinkrate="             ,Drinkrate, 
                                          ",MW="                    ,MW,
                                          ",logP="                  ,logP,
                                          ",VP="                    ,VP,
                                          ",Kpve="                  ,Kpve,
                                          ",Kpsc="                  ,Kpsc,
                                          ",Oralexpo="              ,0,
                                          ",Drinkconc="             ,Drinkconc,
                                          ",Cinh="                  ,Cinh,
                                          ",Cdermal="               ,Cdermal,
                                          ",Tmc="                   ,Tmc,
                                          ",Kt="                    ,Kt,
                                          ",kurinec="               ,kurinec,
                                          ",CLfaeces="              ,CLfaeces,
                                          ",Free="                  ,Free,
                                          ",PL="                    ,PL,
                                          ",PF="                    ,PF,
                                          ",PK="                    ,PK,
                                          ",PSk="                   ,PSk,
                                          ",PR="                    ,PR,
                                          ",PG="                    ,PG,
                                          ",PLun="                  ,PLun,
                                          ",maternal="              ,maternal,
                                          ",PT="                    ,PT,
                                          ",Ratio="                 ,Ratio,
                                          ",DECLINE="               ,DECLINE,
                                          ",Milkconsumption="       ,Milkconsumption,
                                          ",Aartbirth="             ,Aartbirth,
                                          ",Avenbirth="             ,Avenbirth,
                                          ",AGbirth="               ,AGbirth,
                                          ",ALbirth="               ,ALbirth,
                                          ",AFbirth="               ,AFbirth,
                                          ",AKbirth="               ,AKbirth,
                                          ",ALunbirth="             ,ALunbirth,
                                          ",ASkbirth="              ,ASkbirth,
                                          ",ARbirth="               ,ARbirth,
                                          ",Afilbirth="             ,Afilbirth,
                                          ",Adelaybirth="           ,Adelaybirth,
                                          ",Aurinebirth="           ,Aurinebirth,")"))))

  previous.diff<-Inf
  diff<-Inf
  loop<-2
  while(loop<=max.loops&diff>max.diff) {
    y[loop]<-eval(parse(text=paste0(FUN,"("                   ,
                                    "age="                    ,age,
                                    ",BW="                    ,BW,
                                    ",height="                ,height,
                                    ",Gender='"               ,Gender,
                                    "',TSTART="               ,TSTART,
                                    ",TSTOP="                 ,TSTOP,                
                                    ",DT="                    ,DT,                  
                                    ",exposure_duration="     ,exposure_duration,
                                    ",age_start_occ_exp="     ,age_start_occ_exp,
                                    ",age_stop_occ_exp="      ,age_stop_occ_exp,
                                    ",age_start_menstruation=",age_start_menstruation,
                                    ",age_stop_menstruation=" ,age_stop_menstruation,
                                    ",BWbirth="               ,BWbirth,   
                                    ",MFV="                   ,MFV,
                                    ",HR="                    ,HR,  
                                    ",SDLun="                 ,SDLun,     
                                    ",SDH="                   ,SDH,   
                                    ",SDK="                   ,SDK,   
                                    ",SDSto="                 ,SDSto,     
                                    ",SDInt="                 ,SDInt,     
                                    ",SDSpl="                 ,SDSpl,     
                                    ",SDPan="                 ,SDPan,     
                                    ",SDL="                   ,SDL,   
                                    ",SDBon="                 ,SDBon,     
                                    ",SDSk="                  ,SDSk,    
                                    ",SDAdi="                 ,SDAdi,     
                                    ",SDBra="                 ,SDBra,     
                                    ",SDThy="                 ,SDThy,   
                                    ",SDGon="                 ,SDGon, 
                                    ",SDB="                   ,SDB, 
                                    ",SDRem="                 ,SDRem,   
                                    ",QfilC="                 ,QfilC,
                                    ",Htc="                   ,Htc,
                                    ",VplasC="                ,VplasC,
                                    ",VartC="                 ,VartC,
                                    ",VvenC="                 ,VvenC,
                                    ",SkinThickness="         ,SkinThickness,
                                    ",fss="                   ,fss,
                                    ",hsc="                   ,hsc,
                                    ",hve="                   ,hve,
                                    ",ffatsc="                ,ffatsc,
                                    ",ffatve="                ,ffatve,
                                    ",ffatepi="               ,ffatepi,
                                    ",ffatbl="                ,ffatbl,
                                    ",Kpcell="                ,Kpcell, 
                                    ",Drinkrate="             ,Drinkrate, 
                                    ",MW="                    ,MW,
                                    ",logP="                  ,logP,
                                    ",VP="                    ,VP,
                                    ",Kpve="                  ,Kpve,
                                    ",Kpsc="                  ,Kpsc,
                                    ",Oralexpo="              ,x[loop],
                                    ",Drinkconc="             ,Drinkconc,
                                    ",Cinh="                  ,Cinh,
                                    ",Cdermal="               ,Cdermal,
                                    ",Tmc="                   ,Tmc,
                                    ",Kt="                    ,Kt,
                                    ",kurinec="               ,kurinec,
                                    ",CLfaeces="              ,CLfaeces,
                                    ",Free="                  ,Free,
                                    ",PL="                    ,PL,
                                    ",PF="                    ,PF,
                                    ",PK="                    ,PK,
                                    ",PSk="                   ,PSk,
                                    ",PR="                    ,PR,
                                    ",PG="                    ,PG,
                                    ",PLun="                  ,PLun,
                                    ",maternal="              ,maternal,
                                    ",PT="                    ,PT,
                                    ",Ratio="                 ,Ratio,
                                    ",DECLINE="               ,DECLINE,
                                    ",Milkconsumption="       ,Milkconsumption,
                                    ",Aartbirth="             ,Aartbirth,
                                    ",Avenbirth="             ,Avenbirth,
                                    ",AGbirth="               ,AGbirth,
                                    ",ALbirth="               ,ALbirth,
                                    ",AFbirth="               ,AFbirth,
                                    ",AKbirth="               ,AKbirth,
                                    ",ALunbirth="             ,ALunbirth,
                                    ",ASkbirth="              ,ASkbirth,
                                    ",ARbirth="               ,ARbirth,
                                    ",Afilbirth="             ,Afilbirth,
                                    ",Adelaybirth="           ,Adelaybirth,
                                    ",Aurinebirth="           ,Aurinebirth,")")))
    x[loop+1]<-x[loop]+(c-y[loop])*((x[loop]-x[loop-1]))/(y[loop]-y[loop-1])
    
    diff<-abs(c-y[length(y)])

    previous.diff<-diff
    loop<-loop+1
  }
  
  print(paste0("Approximate solution found after ",loop-1," loops. Error of the estimate ≤ ",round(previous.diff,3-round(log10(previous.diff))),"."))
  return(x[length(x)])
}